# postgresql

version: '3.9'

services:
  postgresql:
    image: postgres:16.1
    container_name: local-postgresql
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qwerqwer
      POSTGRES_DB: api
    ports:
      - '5432:5432'
  redis:
    image: redis:7
    container_name: local-redis
    restart: always
    ports:
      - '6379:6379'
